config/routes.rb
Rails.application.routes.draw do
	
	resources :people

	root 'index#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
	validates :name, presence: true,
		length: { maximum: 16 }
	validates :weight, :height, presence: true,
		numericality: { only_integer: true },
		length: { maximum: 3 }
	validates :color, inclusion: {
		in: %w(red orange yellow green blue indigo purple black white),
		message: "can only be one of red, orange, yellow, green, blue, indigo, purple, black, or white"
	}
	validates :stylishness, inclusion: {
		in: %w(none some very),
		message: "can only be one of none, some, or very"
	}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def index
	  @person = Person.all
  end

  def show
	  @person = Person.find(params[:id])
  end

  def new
  end 

  def create
	  render plain: params[:person].inspect
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
    def export
        @person = Person.find(params[:id]) 
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
	def new
		@person = Person.new
	end

	def edit
		@person = Person.find(params[:id])
	end

	def	create
		@person = Person.new(person_params)

		if @person.save
			redirect_to @person
		else
			render 'new'
		end
	end

	def update
		@person = Person.find(params[:id])

		if @person.update(person_params)
			redirect_to @person
		else
			render 'edit'
		end
	end

	def destroy
		@person = Person.find(params[:id])
		@person.destroy

		redirect_to people_path
	end

	private
	def person_params
		params.require(:person).permit(:name,:weight,:height,:color,:stylishness)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/index/index.html.erb
<h1>RectangleDanceParty</h1>
<div class="center-box">
    <p>A rectangle with stylishness set to <em>none</em>
        will move very quickly and ungracefully.
        A rectangle with stylishness set to <em>some</em>
        will move slightly less quickly.
        A rectangle with stylishness set to <em>very</em>
        will move slowly and gracefully.</p>
    <p><strong>Hover over a rectangle to let it know
        it's being watched. Nobody likes dancing while being
        watched.</strong></p>
    <div id="wrap">
        <div id="disp-box">
            <% @person.find_each do |pe| %>
                <% wght = (pe.weight.to_i - (pe.name.length + 15))/5 %>
                <% hght = (pe.height.to_i * 1.4) %>
                <% if wght < 5 %>
                    <% wght = 5 %>
                <% end %>
                <% if hght < 5 %>
                    <% hght = 5 %>
                <% end %>
                <div class="<%=pe.color%> <%=pe.stylishness%>" style="padding-right:<%=wght%>px;padding-bottom:<%=hght%>px"><%=pe.name%><br><span class="stil">(<%=pe.stylishness%>)</span></div>
            <% end %>
        </div>
    </div>
    <p class="stil">If the rectangles refuse to dance, you may need to
        refresh the page. 🐵</p>
    <div class="btns">
        <%= link_to 'People', controller: 'people' %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>A2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
    <% if @person.errors.any? %>
        <div id="error-expl">
            <h2>
                <%= pluralize(@person.errors.count, "error") %> prevented this person from being saved:
            </h2>
            <ul>
                <% @person.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <p>
		<%= f.label :name %><br>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :weight %><br>
		<%= f.text_field :weight %>
	</p>
	<p>
		<%= f.label :height %><br>
		<%= f.text_field :height %>
	</p>
	<p>
		<%= f.label :color %><br>
		<%= f.text_field :color %>
	</p>
	<p>
		<%= f.label :stylishness %><br>
		<%= f.text_field :stylishness %>
	</p>
	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/people/edit.html.erb
<h1>RectangleEdit</h1>
<div class="center-box">
    <%= render 'form' %>
    <div class="btns">
    	<%= link_to 'Back', people_path %>
    </div>
</div>

app/views/people/index.html.erb
<h1><%= link_to 'RectangleDB', "/" %></h1>

<div class="center-box">
	<p>Click on a name to view that Rectangle's stats</p>
	<table>
		<tr>
			<th></th>
			<th>Name</th>
			<th>Weight</th>
			<th>Height</th>
			<th>Color</th>
			<th>Stylishness</th>
		</tr>
		<% count = 0 %>
		<% @person.each do |person| %>
			<tr>
				<% count = count + 1 %>
				<td><%=count%></td>
				<td><%=link_to person.name, person_path(person)%></td>
				<td><%= person.weight %></td>
				<td><%= person.height %></td>
				<td><%= person.color %></td>
				<td><%= person.stylishness %></td>
			</tr>
		<% end %>
	</table>

	<div class="btns">
		<%= link_to 'New', new_person_path %>
		<%= link_to 'Back', "/" %>
	</div>
</div>

app/views/people/new.html.erb
<h1><%= link_to 'RectangleNew', "/" %></h1>
<div class="center-box">
	<%= render 'form' %>
	<div class="btns">
		<%= link_to 'Back', people_path %>
	</div>
</div>

app/views/people/show.html.erb
<h1><%= link_to 'RectangleShow', "/" %></h1>

<div class="center-box">
	<h2><%= @person.name %></h2>
	<p>
		<strong>Weight:</strong>
		<%= @person.weight %>
	</p>
	<p>
		<strong>Height:</strong>
		<%= @person.height %>
	</p>
	<p>
		<strong>Color:</strong>
		<%= @person.color %>
	</p>
	<p>
		<strong>Stylishness:</strong>
		<%= @person.stylishness %>
	</p>
	<div class="btns">
		<%= link_to 'Edit', edit_person_path(@person) %>
		<%= link_to 'Remove', person_path(@person),
			method: :delete,
			data: { confirm: 'Are you sure you want to remove this person?' } %>
		<%= link_to 'Back', people_path %>
	</div>
</div>